require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Rails/HasAndBelongsToMany:
  Enabled: false
