require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

AllCops:
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'genron_sf/spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails:
  Exclude:
    - 'genron_sf/**/*'

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
