require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
