name: DB Schema

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry-run
        required: false
        default: 'true'

jobs:
  Ridgepole:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1

      - name: Bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-20201205-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-20201205-

      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - run: bin/rake ridgepole:apply
        env:
          RAILS_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DRY_RUN: ${{ github.event.inputs.dry-run }}
